### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by rktjmp** [cesc1989/bowlarama-elixir#1]
https://github.com/cesc1989/bowlarama-elixir/blob/ce13ab81f13846697f9baed743aea2ee75f5afc1/lib/bowlarama.ex#L35-L39

Should probably be a pipeline.

---

https://github.com/cesc1989/bowlarama-elixir/blob/ce13ab81f13846697f9baed743aea2ee75f5afc1/lib/players.ex#L17-L25

Without looking too hard, I assume this is a tuple for "player 1" and "player 2" ordering? Why can the players parameter be a list and not `{p_1, p_2}` which then will naturally guard against one or three players? You can then drop the List.first() for pattern matching the function header.

Also the @doc should maybe demonstrate the tuple structure, unsure if the current comment is correct or not.

---

https://github.com/cesc1989/bowlarama-elixir/blob/ce13ab81f13846697f9baed743aea2ee75f5afc1/lib/players.ex#L27-L33

It is more normal to lead with the pipe operator: (applies to a lot of the code)

```elixir
scores
|> Enum.reduce(...)
|> Frame.frames()
|> organize_scores()
```

---
https://github.com/cesc1989/bowlarama-elixir/blob/ce13ab81f13846697f9baed743aea2ee75f5afc1/lib/score.ex#L37-L41

Could maybe be

```elixir
case r in 0..10 do
  true -> r
  false -> raise(...)
end
``` 

---

https://github.com/cesc1989/bowlarama-elixir/blob/ce13ab81f13846697f9baed743aea2ee75f5afc1/lib/score_card.ex#L30

Can just do

```elixir
defp strike_or_spare(["10" | _last]), do: @single_tab <> "X"
```

Though then it's not in the same style as the next function, so... I would probably have kept it as you have. That or have different functions for `[_, "F" | _rest]` and `["F", _ | rest]`.

**Comment by cesc1989** [comment]
Thanks a lot @rktjmp

**Comment by cesc1989** [comment]
Hey @rktjmp just applied your feedback (was adding tests to learn) and def the code looks more succinct.

Regarding:
```elixir
defp strike_or_spare(["10" | _last]), do: @single_tab <> "X"
```

I had it in mind but preferred someone would point out to see if it's something done regularly.

Thanks again!
